version: '2.2'

services:
    mysql:
        container_name: container_mysql_maa
        image: mysql:5.7
        volumes:
            - "./../docker/volumes/maa/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        ports:
            - "3306:3306"
    php:
        container_name: container_phpfpm_maa
        build:
            context: docker/php8-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./:/var/www/maa
    nginx:
        container_name: container_nginx_maa
        build:
            context: docker/nginx
            args:
                MAX_EXECUTION_TIME: ${MAX_EXECUTION_TIME}
        ports:
            - "80:80"
        volumes_from:
            - php
        volumes:
            - "./../docker/volumes/maa/logs/nginx/:/var/log/nginx"
